version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
     - POSTGRES_DB=db_orm
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mysql:
    image: mysql:5
    environment:
     - MYSQL_DATABASE=db_orm
     - MYSQL_USER=root
     - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - MYSQL_ROOT_PASSWORD=123
     - PMA_HOST=mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
